trigger: none

pool: 2026-pool

steps:

- script: |
    echo "Default working dir:"
    echo $(System.DefaultWorkingDirectory)

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'Demo-Service Connection'
    backendAzureRmResourceGroupName: 'demo-rg'
    backendAzureRmStorageAccountName: 'demosstg123'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Demo-Service Connection'

- task: TerraformTask@5
  displayName: Terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Demo-Service Connection'
