trigger: none

pool: 2026-pool

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/main'
    backendServiceArm: 'Demo-Service Connection'
    backendAzureRmResourceGroupName: 'demo-rg'
    backendAzureRmStorageAccountName: 'demosstg123'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/main'
    environmentServiceNameAzureRM: 'Demo-Service Connection'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/main'
    environmentServiceNameAzureRM: 'Demo-Service Connection'