trigger: none

pool: 2026-pool

steps:

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/sandeep-git-repo'
    backendServiceArm: 'Demo-Service Connection'
    backendAzureRmResourceGroupName: 'demo-rg'
    backendAzureRmStorageAccountName: 'demosstg123'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

